[package]
name = "beginner_tutorial"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12.1"

#Включает небольшую оптимизацию в режиме отладки
[profile.dev]
opt-level = 1

#Включает высокую оптимизацию зависимостей (включая. Bevy)
[profile.dev.package."*"]
opt-level = 3
